version: '3.7'

services:
    db:
        image: mongo:4.0.4
        container_name: db
        restart: always
        ports:
            - '27017:27017'
        volumes:
            - ./data/db:/data/db
        networks:
            - app-network

    backend:
        build: ./backend
        container_name: backend
        restart: always
        ports:
            - 5000:5000
        depends_on:
            - db
        networks:
            - app-network
        env_file:
            - .env

#    frontend:
#        build: ./frontend
#        container_name: frontend
#        restart: always
#        ports:
#            - 3000:3000
#        networks:
#            - app-network
#        env_file:
#            - .env.development.local

networks:
    app-network:
        driver: bridge


